# Generated by Django 5.1.7 on 2025-03-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=100)),
                ('nivel_perigo', models.IntegerField(max_length=3)),
                ('nivel_extincao', models.IntegerField(max_length=3)),
                ('descricao', models.TextField()),
            ],
        ),
    ]
