# Generated by Django 5.1.7 on 2025-03-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_animais_nivel_extincao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animais',
            name='nivel_extincao',
            field=models.CharField(max_length=100),
        ),
    ]
